apiVersion: apps/v1
kind: Deployment
metadata:
    name: star-wars-deployment
spec:
    selector:
        matchLabels:
            app: star-wars
    replicas: 2
    template:
        metadata:
            labels:
                app: star-wars
        spec:
            containers:
                - name: star-wars
                  image: so2liu/starwars-node
                  ports:
                      - containerPort: 3000
                  env:
                      - name: MAX_STAR_WARS_CHARACTERS
                        valueFrom:
                            configMapKeyRef:
                                name: sw-envs
                                key: maxStarWarsCharacters
